version: '3'
services:
  server:
    container_name: eoc_server_container
    restart: always
    build: .
    image: "${BRANCH_NAME}:${BUILD_NUMBER}"
    ports:
      - '8080:8080'
    links:
      - mongo
    environment:
      DB_URL: mongodb://mongo:27017
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
