version: '3'

services:
  eoc-server:
    container_name: eoc_server_container
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    ports:
      - '8080'
    links:
      - mongo
    environment:
      DB_URL: mongodb://mongo/eoc
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      EXPRESS_SESSION_KEY:
  nginx-production:
    container_name: eoc_nginx_production
    restart: always
    build: ./nginx
    ports:
      - '81:80'
    volumes:
      -  /etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    links:
      - eoc-server
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - '27017'
