version: '3'
services:
  server:
    container_name: eoc_server_container
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    ports:
      - '80:80'
    links:
      - mongo
    environment:
      DB_URL: mongodb://mongo/eoc
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      EXPRESS_SESSION_KEY:
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db
    ports:
      - '127.0.0.1:38128:27017'
